SE-30 sdk
polyse/database-sdk pull request #1
Opened 2020-05-12 16:25 UTC by KudinovKV

2020-05-12 16:49 UTC, senyasdt requested changes
Мне кажется стоитло написать полноценного клиента, которму передают url мастера базы данных и у его просто есть метод примерно такой сигнатуры
```go

func NewDbClient(url string) *DbClient {
}

func (c *DbClient) saveData(collectionName string, data []RawData) error {
 ...
}

2020-05-12 16:54 UTC, senyasdt requested changes

2020-05-12 16:54 UTC, senyast4745 commented on sdk.go
> +	resp, err := http.Post("/api/"+p.collectionName+"/documents", "application/json", bytes.NewBuffer(requestBody))
Тут навреное лучше `fmt.Sprintf("/api/%s/documents", p.collectionName)` И навреное "applicaton/json"  и вот эту штуку следовало бы вынести в блок var наверх

2020-05-12 16:54 UTC, senyast4745 commented on sdk.go
> +func (p *PolySEDB) Add() error {
Наверное следвало как я уже говорил запилить клиента и уже ему передавать эту PolySEDB, хотя особо смысла в ней я не вижу

2020-05-12 16:55 UTC, KudinovKV commented on sdk.go
> +func (p *PolySEDB) Add() error {
По сути это название поменять?

2020-05-12 16:56 UTC, KudinovKV commented on sdk.go
> +func (p *PolySEDB) Add() error {
И чуть по другому параметры передать

2020-05-12 17:02 UTC, senyast4745 commented on sdk.go
> +func (p *PolySEDB) Add() error {
По другому инициализировать. Я в коммене выше написал так как думаю я

2020-05-12 17:35 UTC, KudinovKV commented on sdk.go
> +func (p *PolySEDB) Add() error {
Так если так сделать, внутри **DBClient** хранить нечего. **Url** при инициализации то не нужен, он итак хранится в **RawData**. Нет?

2020-05-12 17:45 UTC, senyast4745 commented on sdk.go
> +func (p *PolySEDB) Add() error {
нет, тебе нужен **url базы данных**,чтобы отправлять ей запросы,  а в RawData хранится url сайта, который мы прочитали

2020-05-12 17:46 UTC, senyast4745 commented on sdk.go
> +func (p *PolySEDB) Add() error {
Ты же не знаешь на каком хосте запущенна база данных, так что отправлять запрос по сути некуда

2020-05-13 08:54 UTC, KudinovKV commented on sdk.go
> +func (p *PolySEDB) Add() error {
А, понял о чем ты

2020-05-13 09:21 UTC, TarIvAl commented on sdk.go
> +	Data string `json:"Data"`
в теге Data  с большой буквы, это не вызовет проблем в последствии?

2020-05-13 09:22 UTC, KudinovKV commented on sdk.go
> +	Data string `json:"Data"`
А у всех с маленькой?

2020-05-13 09:24 UTC, TarIvAl commented on sdk.go
> +	} else if resp.StatusCode == http.StatusOK {
else здесь лишний по кодстайлу

2020-05-13 09:28 UTC, KudinovKV commented
При merge структурки, которые тут есть уйдут, только DBClient останется

2020-05-13 09:31 UTC, TarIvAl commented on sdk.go
> +	Data string `json:"Data"`
да

2020-05-13 09:32 UTC, senyasdt approved these changes

2020-05-13 09:34 UTC, KudinovKV commented on sdk.go
> +	Data string `json:"Data"`
Поправил

2020-05-15 12:39 UTC, TarIvAl approved these changes

2020-05-15 17:40 UTC, tariel-x commented on sdk.go
> +	resp, err := http.Post(fmt.Sprintf("%s/api/%s/documents", d.url, collectionName), contentType, bytes.NewBuffer(requestBody))
Очень опасный момент - использовать клиент по-умолчанию. Там таймаут 0, то есть и бесконечность не предел.

2020-05-15 17:42 UTC, tariel-x commented on sdk.go
> +	_ = json.NewDecoder(resp.Body).Decode(&answer)
Может прийти битый json, например, если база за nginx и тот вернул 200 с html. Надо проверить, что распарсилось корректно.

2020-05-15 17:43 UTC, tariel-x commented on sdk.go
> +	} else if resp.StatusCode == http.StatusOK {
Не покрывает 201 Created.

2020-05-15 17:45 UTC, tariel-x commented on sdk.go
> +	_ = json.NewDecoder(resp.Body).Decode(&answer)
А вообще, там вроде структура с message возвращается по-умолчанию в echo в базе.

2020-05-16 12:22 UTC, KudinovKV commented
Логика такая.
1. Если получил resp с ошибкой, вернул []Documents, err
2. Если код не 200/201 вернул []Documents, err
3. Начинаю парсить, если не распарсилось, вернул []Documents, "Не смог распарсить"
4. Если распарсил, смотрю `Message`, если там нет 200/201, значит не вставилось в бд, возвращаю ошибку, которую получил от бд и []InsertedDocuments
5. Если нашел 200/201 в сообщении, то вернул []InsertedDocuments, nil
6. Если `Message` не получил вообще, то вернул []Documents, "Unexpected answer"

2020-05-16 12:24 UTC, tariel-x commented on sdk.go
> +	client := http.Client{
Клиента можно создать один раз в методе NewDBClient.

2020-05-16 12:26 UTC, tariel-x commented on sdk.go
> +		return data, errors.New(http.StatusText(resp.StatusCode))
Мне кажется, было бы правильней читать ответ от базы, что именно она вставила. Это несложно и пригодится если/когда появятся ID документов.

2020-05-16 12:28 UTC, tariel-x commented on sdk.go
> +		return data, err
Здесь лучше вернуть `nil, fmt.Errorf("can not perform request: %w", err)`

2020-05-16 12:31 UTC, tariel-x commented on sdk.go
> +		return data, errors.New(http.StatusText(resp.StatusCode))
Мне кажется, надо сначала посмотреть, что вернулось от базы, может быть там есть подробный message с ошибкой валидаци, например. Иначе прямо тут вернётся 400 bad request, а подробности от базы будут проигнорированы.

2020-05-16 12:32 UTC, tariel-x commented on sdk.go
> +		return data, err
Тут бы тоже обернуть ошибку типа `nil, fmt.Errorf("unexpected answer: %w", err)`

2020-05-16 12:36 UTC, tariel-x commented on sdk.go
> +		if strings.Contains(res.Message, "200") == true || strings.Contains(res.Message, "201") == true {
Я написал в комментариях к тому pr https://github.com/polyse/database/pull/4/files#r426149912 , что в случае 201 никакого дополнительного message не требуется. И тут учитывать не стоит, я полагаю.

2020-05-16 13:10 UTC, tariel-x commented
> Логика такая.
> 
>     1. Если получил resp с ошибкой, вернул []Documents, err
> 
>     2. Если код не 200/201 вернул []Documents, err
> 
>     3. Начинаю парсить, если не распарсилось, вернул []Documents, "Не смог распарсить"
> 
>     4. Если распарсил, смотрю `Message`, если там нет 200/201, значит не вставилось в бд, возвращаю ошибку, которую получил от бд и []InsertedDocuments
> 
>     5. Если нашел 200/201 в сообщении, то вернул []InsertedDocuments, nil
> 
>     6. Если `Message` не получил вообще, то вернул []Documents, "Unexpected answer"

1. Если запрос не выполнился, то вернулось err и документы возвращать не требуется, можно nil.
2. Если 201 и ответ парсится в структуру документов - вернуть возвращённые документы и nil вместо ошибки.
3.1 Если 201, но ответ не парсится - nil, unexpected answer
3. Если код 400+, попробовать прочитать message и вернуть его как ошибку.
4. Если ответ не читается, вернуть unexpected answer

В идеале бы ещё завести для 400-х ответов какую-нибудь ошкибку типа `var BadRequest = errors.New("bad request")` и возвращать их вместе с текстом из message так типа `fmt.Errorf("%w: %s", BadRequest, resp.Message)`, чтоб потом можно было сделать `errors.Is(err, sdk.BadRequest)`.

Механизм такой: https://play.golang.com/p/ZCP8aTPl7ED

2020-05-16 13:12 UTC, tariel-x commented
Но отдельная обработка 400-х и errors.Is пока не важны, можно в дальнейшем докрутить.

2020-05-16 13:23 UTC, KudinovKV commented
Логика такая как написано, пока только не смотрю на код 400+ или нет

2020-05-16 13:35 UTC, tariel-x commented on sdk.go
> +	} else {
Лишний else, потому что выше есть return.

2020-05-16 13:36 UTC, tariel-x commented on sdk.go
> +		return Documents{}, fmt.Errorf("Unexpected answer: %w", err)
Лучше изменить сигнатуру фукнции на `*Documents, error` или вообще на `[]Document, error` и тогда возвращать `nil, err`.

2020-05-16 13:39 UTC, tariel-x commented on sdk.go
> +		return Documents{}, fmt.Errorf("Unexpected answer: %w", err)
Потому что так выделяется память под пустую структуру и все пустые поля.

2020-05-16 15:13 UTC, tariel-x approved these changes

2020-05-16 15:23 UTC, merged